### PR TITLE
Jw image tag, through act_as_taggable

### PR DESCRIPTION
**Pull request by jarwil96**
Closes issue #4

### CODE REVIEW

**Comment by jarwil96** [comment]
[Issue 4: Image Tags](https://trello.com/c/Mswx8jPt/6-issue-4-image-tags)

**Comment by bboe** [comment]
Just out of curiosity, how did I get added as a reviewer to this issue?

**Comment by jarwil96** [comment]
Hi,

I was following Justin's instructions by just adding the github suggested
reviewer for the ropes project PRs. I apologize I thought that was just
part of the process since I was instructed to do so. I will stop adding you
from now on haha.

Jared

**Comment by bboe** [comment]
No worries, I was just curious. Perhaps let Justin know that the suggestions may not be 100% accurate.

**Comment by jarwil96** [comment]
Sounds good, will do

Jared

**Comment by jarwil96** [comment]
[Issue 5: Images by Tag](https://trello.com/c/muMA6zhl/5-issue-5-images-by-tag)

**Pull request merged**
